name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest

      - name: Import sanity
        run: |
          python - <<'PY'
          import importlib
          for m in ["tensorflow", "streamlit", "pandas", "numpy"]:
              importlib.import_module(m)
          print("✅ Imports OK")
          PY

      - name: Run tests (if present)
        run: |
          if [ -d tests ] || ls -1 *.py src/*.py 2>/dev/null | grep -q .; then
            pytest -q || echo "⚠️ Tests failed (non-blocking)"
          else
            echo "ℹ️ No tests found; skipping"
          fi
